In [1]:
from sklearn.preprocessing import StandardScaler
import pandas as pd

In [3]:
train_data = pd.read_csv('../data/raw/train.csv')
print(train_data.shape)
train_data.head()

(891, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [28]:
train_data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

### Missing values

In [29]:
null_cols = train_data.isnull().sum()
duplicated_rows = train_data.duplicated().sum()
print('Missing values:\n', null_cols)
print('Duplicated rows: ', duplicated_rows)
train_data.head()

Missing values:
 PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64
Duplicated rows:  0

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [30]:
train_data['Age'] = train_data['Age'].fillna(train_data['Age'].median())
train_data['Embarked'] = train_data['Embarked'].fillna(train_data['Embarked'].mode()[0])
train_data['Sex'] = train_data['Sex'].map({'male':0, 'female': 1})
train_data['FamilySize'] = train_data['SibSp'] + train_data['Parch'] + 1
train_data['IsAlone'] = (train_data['FamilySize'] == 1).astype(int)

train_data = train_data.drop(columns=['Name', 'PassengerId', 'Cabin', 'Ticket'])

In [31]:
scaler = StandardScaler()

train_data[['Age', 'Fare']] = scaler.fit_transform(train_data[['Age', 'Fare']])

In [32]:
train_data.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,FamilySize,IsAlone
0,0,3,0,-0.565736,1,0,-0.502445,S,2,0
1,1,1,1,0.663861,1,0,0.786845,C,2,0
2,1,3,1,-0.258337,0,0,-0.488854,S,1,1
3,1,1,1,0.433312,1,0,0.420730,S,2,0
4,0,3,0,0.433312,0,0,-0.486337,S,1,1

In [33]:
print(train_data['Embarked'].unique())
train_data = pd.get_dummies(train_data, 
               columns=['Embarked'], 
               drop_first=True)

train_data.head()

<StringArray>
['S', 'C', 'Q']
Length: 3, dtype: str

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,FamilySize,IsAlone,Embarked_Q,Embarked_S
0,0,3,0,-0.565736,1,0,-0.502445,2,0,False,True
1,1,1,1,0.663861,1,0,0.786845,2,0,False,False
2,1,3,1,-0.258337,0,0,-0.488854,1,1,False,True
3,1,1,1,0.433312,1,0,0.420730,2,0,False,True
4,0,3,0,0.433312,0,0,-0.486337,1,1,False,True

In [ ]:
test_data = pd.read_csv('../data/raw/test.csv')
print(test_data.shape)
test_data.head()

(418, 11)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [35]:
null_cols = test_data.isnull().sum()
duplicated_rows = test_data.duplicated().sum()
print('Missing values:\n', null_cols)
print('Duplicated rows: ', duplicated_rows)

Missing values:
 PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64
Duplicated rows:  0

In [ ]:
test_data['Age'] = test_data['Age'].fillna(test_data['Age'].median())
test_data['Fare'] = test_data['Fare'].fillna(test_data['Fare'].median())
test_data['Sex'] = test_data['Sex'].map({'male':0, 'female': 1})
test_data['FamilySize'] = test_data['SibSp'] + test_data['Parch'] + 1
test_data['IsAlone'] = (test_data['FamilySize'] == 1).astype(int)

test_data = test_data.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin'])
test_data[['Age', 'Fare']] = scaler.transform(test_data[['Age', 'Fare']])

In [37]:
test_data = pd.get_dummies(test_data,
                           columns=['Embarked'],
                           drop_first=True)

In [38]:
print(train_data.shape)
train_data.head()

(891, 11)

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,FamilySize,IsAlone,Embarked_Q,Embarked_S
0,0,3,0,-0.565736,1,0,-0.502445,2,0,False,True
1,1,1,1,0.663861,1,0,0.786845,2,0,False,False
2,1,3,1,-0.258337,0,0,-0.488854,1,1,False,True
3,1,1,1,0.433312,1,0,0.420730,2,0,False,True
4,0,3,0,0.433312,0,0,-0.486337,1,1,False,True

In [39]:
print(test_data.shape)
test_data.head()

(418, 10)

,Pclass,Sex,Age,SibSp,Parch,Fare,FamilySize,IsAlone,Embarked_Q,Embarked_S
0,3,0,0.394887,0,0,-0.490783,1,1,True,False
1,3,1,1.355510,1,0,-0.507479,2,0,False,True
2,2,0,2.508257,0,0,-0.453367,1,1,True,False
3,3,0,-0.181487,0,0,-0.474005,1,1,False,True
4,3,1,-0.565736,1,1,-0.401017,3,0,False,True

In [ ]:
train_data.to_csv('../data/processed/train.csv', index=False)
test_data.to_csv('../data/processed/test.csv', index=False)